/**
 * npm run db:bundle
 * Writes database/all_procedures.sql with DELIMITER $$ so every procedure can be
 * deployed from MySQL Workbench / the mysql CLI in one go.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { DB_DIR, procedureFiles, rel } from './lib';

const procs = procedureFiles();
const parts: string[] = [
  '-- WB-POS stored procedures (generated by `npm run db:bundle` - do not edit by hand)',
  `-- Generated: ${new Date().toISOString()}`,
  '',
  'DELIMITER $$',
  '',
];
for (const p of procs) {
  parts.push(`-- ${rel(p.file)}`);
  parts.push(`DROP PROCEDURE IF EXISTS \`${p.name}\`$$`);
  parts.push(`${p.sql}$$`);
  parts.push('');
}
parts.push('DELIMITER ;', '');

const out = join(DB_DIR, 'all_procedures.sql');
writeFileSync(out, parts.join('\n'), 'utf8');
console.log(`Wrote ${procs.length} procedures to ${out}`);
