CREATE TABLE IF NOT EXISTS items (
  id                  INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  item_code           VARCHAR(20)   NOT NULL,
  item_name           VARCHAR(60)   NOT NULL,
  item_type           ENUM('SALE','RAW','BOTH') NOT NULL DEFAULT 'SALE',
  category_id         INT UNSIGNED  NOT NULL,
  unit_id             INT UNSIGNED  NOT NULL,
  selling_price       DECIMAL(12,2) NOT NULL DEFAULT 0,
  purchase_price      DECIMAL(12,2) NOT NULL DEFAULT 0,
  gst_pct             DECIMAL(5,2)  NOT NULL DEFAULT 0,
  price_includes_gst  TINYINT(1)    NOT NULL DEFAULT 1,
  hsn_code            VARCHAR(8)    NULL,
  barcode             VARCHAR(40)   NULL,
  current_stock       DECIMAL(12,3) NOT NULL DEFAULT 0,
  min_stock           DECIMAL(12,3) NOT NULL DEFAULT 0,
  image_url           VARCHAR(255)  NULL,
  status              TINYINT(1)    NOT NULL DEFAULT 1,
  is_deleted          TINYINT(1)    NOT NULL DEFAULT 0,
  created_by          INT           NULL,
  created_at          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by          INT           NULL,
  updated_at          DATETIME      NULL,
  active_code         VARCHAR(20)   GENERATED ALWAYS AS (IF(is_deleted = 0, item_code, NULL)) VIRTUAL,
  active_name         VARCHAR(60)   GENERATED ALWAYS AS (IF(is_deleted = 0, item_name, NULL)) VIRTUAL,
  active_barcode      VARCHAR(40)   GENERATED ALWAYS AS (IF(is_deleted = 0, NULLIF(barcode, ''), NULL)) VIRTUAL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_items_code (active_code),
  UNIQUE KEY uq_items_name (active_name),
  UNIQUE KEY uq_items_barcode (active_barcode),
  KEY ix_items_category (category_id),
  KEY ix_items_unit (unit_id),
  KEY ix_items_status_type (status, item_type),
  CONSTRAINT fk_items_category FOREIGN KEY (category_id) REFERENCES categories (id),
  CONSTRAINT fk_items_unit     FOREIGN KEY (unit_id)     REFERENCES units (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
