CREATE TABLE IF NOT EXISTS suppliers (
  id                  INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  supplier_code       VARCHAR(20)   NOT NULL,
  supplier_name       VARCHAR(80)   NOT NULL,
  contact_person      VARCHAR(80)   NULL,
  mobile              VARCHAR(10)   NOT NULL,
  email               VARCHAR(100)  NULL,
  address             VARCHAR(255)  NULL,
  state_code          CHAR(2)       NOT NULL,
  gstin               VARCHAR(15)   NULL,
  opening_balance     DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_terms_days  INT           NOT NULL DEFAULT 0,
  current_balance     DECIMAL(12,2) NOT NULL DEFAULT 0,
  status              TINYINT(1)    NOT NULL DEFAULT 1,
  is_deleted          TINYINT(1)    NOT NULL DEFAULT 0,
  created_by          INT           NULL,
  created_at          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by          INT           NULL,
  updated_at          DATETIME      NULL,
  active_code         VARCHAR(20)   GENERATED ALWAYS AS (IF(is_deleted = 0, supplier_code, NULL)) VIRTUAL,
  active_name         VARCHAR(80)   GENERATED ALWAYS AS (IF(is_deleted = 0, supplier_name, NULL)) VIRTUAL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_suppliers_code (active_code),
  UNIQUE KEY uq_suppliers_name (active_name),
  KEY ix_suppliers_status (status),
  KEY ix_suppliers_state (state_code),
  CONSTRAINT fk_suppliers_state FOREIGN KEY (state_code) REFERENCES states (state_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
