CREATE TABLE IF NOT EXISTS employee_types (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  type_name    VARCHAR(40)  NOT NULL,
  description  VARCHAR(200) NULL,
  can_login    TINYINT(1)   NOT NULL DEFAULT 0,
  status       TINYINT(1)   NOT NULL DEFAULT 1,
  is_deleted   TINYINT(1)   NOT NULL DEFAULT 0,
  created_by   INT          NULL,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by   INT          NULL,
  updated_at   DATETIME     NULL,
  active_name  VARCHAR(40)  GENERATED ALWAYS AS (IF(is_deleted = 0, type_name, NULL)) VIRTUAL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_employee_types_name (active_name),
  KEY ix_employee_types_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- aadhaar_enc / bank_account_enc are AES-256-GCM ciphertexts produced in Node.
-- aadhaar_hash is an HMAC of the number so duplicates can be detected without decrypting.
CREATE TABLE IF NOT EXISTS employees (
  id                INT UNSIGNED NOT NULL AUTO_INCREMENT,
  emp_code          VARCHAR(20)  NOT NULL,
  photo_url         VARCHAR(255) NULL,
  full_name         VARCHAR(80)  NOT NULL,
  employee_type_id  INT UNSIGNED NOT NULL,
  mobile            VARCHAR(10)  NOT NULL,
  alt_mobile        VARCHAR(10)  NULL,
  email             VARCHAR(100) NULL,
  gender            ENUM('MALE','FEMALE','OTHER') NOT NULL,
  dob               DATE         NULL,
  joining_date      DATE         NOT NULL,
  address           VARCHAR(255) NULL,
  aadhaar_enc       VARCHAR(255) NULL,
  aadhaar_last4     CHAR(4)      NULL,
  aadhaar_hash      CHAR(64)     NULL,
  id_proof_url      VARCHAR(255) NULL,
  id_proof_name     VARCHAR(150) NULL,
  emergency_name    VARCHAR(80)  NULL,
  emergency_mobile  VARCHAR(10)  NULL,
  bank_account_enc  VARCHAR(255) NULL,
  ifsc              VARCHAR(11)  NULL,
  emp_status        ENUM('ACTIVE','RESIGNED') NOT NULL DEFAULT 'ACTIVE',
  resign_date       DATE         NULL,
  is_deleted        TINYINT(1)   NOT NULL DEFAULT 0,
  created_by        INT          NULL,
  created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by        INT          NULL,
  updated_at        DATETIME     NULL,
  active_code       VARCHAR(20)  GENERATED ALWAYS AS (IF(is_deleted = 0, emp_code, NULL)) VIRTUAL,
  active_mobile     VARCHAR(10)  GENERATED ALWAYS AS (IF(is_deleted = 0, mobile, NULL)) VIRTUAL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_employees_code (active_code),
  UNIQUE KEY uq_employees_mobile (active_mobile),
  KEY ix_employees_type (employee_type_id),
  KEY ix_employees_status (emp_status),
  KEY ix_employees_aadhaar (aadhaar_hash),
  CONSTRAINT fk_employees_type FOREIGN KEY (employee_type_id) REFERENCES employee_types (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS employee_advances (
  id                INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  employee_id       INT UNSIGNED  NOT NULL,
  advance_date      DATE          NOT NULL,
  amount            DECIMAL(12,2) NOT NULL,
  recovered_amount  DECIMAL(12,2) NOT NULL DEFAULT 0,
  remarks           VARCHAR(200)  NULL,
  is_deleted        TINYINT(1)    NOT NULL DEFAULT 0,
  created_by        INT           NULL,
  created_at        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by        INT           NULL,
  updated_at        DATETIME      NULL,
  PRIMARY KEY (id),
  KEY ix_employee_advances_emp (employee_id, advance_date),
  CONSTRAINT fk_employee_advances_emp FOREIGN KEY (employee_id) REFERENCES employees (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS salary_setups (
  id              INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  employee_id     INT UNSIGNED  NOT NULL,
  salary_type     ENUM('MONTHLY','DAILY') NOT NULL,
  basic_salary    DECIMAL(12,2) NOT NULL,
  allowances      DECIMAL(12,2) NOT NULL DEFAULT 0,
  effective_from  DATE          NOT NULL,
  is_deleted      TINYINT(1)    NOT NULL DEFAULT 0,
  created_by      INT           NULL,
  created_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by      INT           NULL,
  updated_at      DATETIME      NULL,
  PRIMARY KEY (id),
  KEY ix_salary_setups_emp (employee_id, effective_from),
  CONSTRAINT fk_salary_setups_emp FOREIGN KEY (employee_id) REFERENCES employees (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS salary_payments (
  id                 INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  employee_id        INT UNSIGNED  NOT NULL,
  pay_month          CHAR(7)       NOT NULL COMMENT 'YYYY-MM',
  working_days       DECIMAL(5,1)  NOT NULL,
  days_present       DECIMAL(5,1)  NOT NULL,
  gross_salary       DECIMAL(12,2) NOT NULL DEFAULT 0,
  bonus              DECIMAL(12,2) NOT NULL DEFAULT 0,
  advance_deduction  DECIMAL(12,2) NOT NULL DEFAULT 0,
  other_deduction    DECIMAL(12,2) NOT NULL DEFAULT 0,
  deduction_reason   VARCHAR(200)  NULL,
  net_salary         DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_date       DATE          NULL,
  payment_mode       ENUM('CASH','BANK','UPI') NULL,
  pay_status         ENUM('PENDING','PAID') NOT NULL DEFAULT 'PENDING',
  is_deleted         TINYINT(1)    NOT NULL DEFAULT 0,
  created_by         INT           NULL,
  created_at         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by         INT           NULL,
  updated_at         DATETIME      NULL,
  active_key         VARCHAR(20)   GENERATED ALWAYS AS (IF(is_deleted = 0, CONCAT(employee_id, ':', pay_month), NULL)) VIRTUAL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_salary_payments_emp_month (active_key),
  KEY ix_salary_payments_emp (employee_id),
  KEY ix_salary_payments_month (pay_month, pay_status),
  CONSTRAINT fk_salary_payments_emp FOREIGN KEY (employee_id) REFERENCES employees (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
