CREATE TABLE IF NOT EXISTS customers (
  id             INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  mobile         VARCHAR(10)   NOT NULL,
  customer_name  VARCHAR(80)   NULL,
  total_spent    DECIMAL(12,2) NOT NULL DEFAULT 0,
  visit_count    INT           NOT NULL DEFAULT 0,
  last_visit_at  DATETIME      NULL,
  created_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     DATETIME      NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_customers_mobile (mobile)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- item_count / payment_mode are denormalised by sp_bill_save so the list screens never aggregate.
CREATE TABLE IF NOT EXISTS bills (
  id               INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  bill_no          VARCHAR(20)   NULL,
  bill_date        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  client_ref       CHAR(36)      NULL COMMENT 'Device UUID for offline idempotency',
  device_id        VARCHAR(50)   NULL,
  customer_id      INT UNSIGNED  NULL,
  customer_mobile  VARCHAR(10)   NULL,
  customer_name    VARCHAR(80)   NULL,
  item_count       INT           NOT NULL DEFAULT 0,
  sub_total        DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount_type    ENUM('AMOUNT','PERCENT') NOT NULL DEFAULT 'AMOUNT',
  discount_value   DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount_amount  DECIMAL(12,2) NOT NULL DEFAULT 0,
  taxable_amount   DECIMAL(12,2) NOT NULL DEFAULT 0,
  cgst             DECIMAL(12,2) NOT NULL DEFAULT 0,
  sgst             DECIMAL(12,2) NOT NULL DEFAULT 0,
  round_off        DECIMAL(12,2) NOT NULL DEFAULT 0,
  grand_total      DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_mode     VARCHAR(10)   NULL COMMENT 'CASH | UPI | CARD | SPLIT',
  bill_status      ENUM('HELD','COMPLETED','CANCELLED') NOT NULL,
  cancel_reason    VARCHAR(200)  NULL,
  cancelled_by     INT UNSIGNED  NULL,
  cancelled_at     DATETIME      NULL,
  cashier_id       INT UNSIGNED  NOT NULL,
  is_deleted       TINYINT(1)    NOT NULL DEFAULT 0,
  created_by       INT           NULL,
  created_at       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by       INT           NULL,
  updated_at       DATETIME      NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_bills_no (bill_no),
  UNIQUE KEY uq_bills_client_ref (client_ref),
  KEY ix_bills_date (bill_date),
  KEY ix_bills_status_date (bill_status, bill_date),
  KEY ix_bills_cashier_date (cashier_id, bill_date),
  KEY ix_bills_customer (customer_id),
  KEY ix_bills_mobile (customer_mobile),
  CONSTRAINT fk_bills_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
  CONSTRAINT fk_bills_cashier  FOREIGN KEY (cashier_id)  REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bill_items (
  id                  INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  bill_id             INT UNSIGNED  NOT NULL,
  line_no             INT           NOT NULL,
  item_id             INT UNSIGNED  NULL,
  combo_id            INT UNSIGNED  NULL,
  item_code           VARCHAR(20)   NULL,
  item_name           VARCHAR(100)  NOT NULL,
  unit_code           VARCHAR(10)   NULL,
  allow_decimal       TINYINT(1)    NOT NULL DEFAULT 0,
  qty                 DECIMAL(12,3) NOT NULL,
  rate                DECIMAL(12,2) NOT NULL,
  gst_pct             DECIMAL(5,2)  NOT NULL,
  price_includes_gst  TINYINT(1)    NOT NULL,
  line_amount         DECIMAL(12,2) NOT NULL,
  discount_share      DECIMAL(12,2) NOT NULL DEFAULT 0,
  taxable_amount      DECIMAL(12,2) NOT NULL,
  cgst                DECIMAL(12,2) NOT NULL,
  sgst                DECIMAL(12,2) NOT NULL,
  line_total          DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (id),
  KEY ix_bill_items_bill (bill_id),
  KEY ix_bill_items_item (item_id),
  KEY ix_bill_items_combo (combo_id),
  CONSTRAINT fk_bill_items_bill  FOREIGN KEY (bill_id)  REFERENCES bills (id),
  CONSTRAINT fk_bill_items_item  FOREIGN KEY (item_id)  REFERENCES items (id),
  CONSTRAINT fk_bill_items_combo FOREIGN KEY (combo_id) REFERENCES combos (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bill_payments (
  id               INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  bill_id          INT UNSIGNED  NOT NULL,
  payment_mode     ENUM('CASH','UPI','CARD') NOT NULL,
  amount           DECIMAL(12,2) NOT NULL,
  reference_no     VARCHAR(50)   NULL,
  cash_received    DECIMAL(12,2) NULL,
  change_returned  DECIMAL(12,2) NULL,
  created_at       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_bill_payments_bill (bill_id),
  KEY ix_bill_payments_mode (payment_mode),
  CONSTRAINT fk_bill_payments_bill FOREIGN KEY (bill_id) REFERENCES bills (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS bill_status_history (
  id           INT UNSIGNED NOT NULL AUTO_INCREMENT,
  bill_id      INT UNSIGNED NOT NULL,
  from_status  VARCHAR(10)  NULL,
  to_status    VARCHAR(10)  NOT NULL,
  remarks      VARCHAR(200) NULL,
  changed_by   INT UNSIGNED NULL,
  changed_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_bill_status_history_bill (bill_id),
  CONSTRAINT fk_bill_status_history_bill FOREIGN KEY (bill_id) REFERENCES bills (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
