CREATE TABLE IF NOT EXISTS purchase_orders (
  id             INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  po_no          VARCHAR(20)   NOT NULL,
  po_date        DATE          NOT NULL,
  supplier_id    INT UNSIGNED  NOT NULL,
  expected_date  DATE          NULL,
  notes          VARCHAR(500)  NULL,
  sub_total      DECIMAL(12,2) NOT NULL DEFAULT 0,
  cgst           DECIMAL(12,2) NOT NULL DEFAULT 0,
  sgst           DECIMAL(12,2) NOT NULL DEFAULT 0,
  igst           DECIMAL(12,2) NOT NULL DEFAULT 0,
  other_charges  DECIMAL(12,2) NOT NULL DEFAULT 0,
  round_off      DECIMAL(12,2) NOT NULL DEFAULT 0,
  grand_total    DECIMAL(12,2) NOT NULL DEFAULT 0,
  po_status      ENUM('DRAFT','SENT','PARTIAL','RECEIVED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  cancel_reason  VARCHAR(200)  NULL,
  is_deleted     TINYINT(1)    NOT NULL DEFAULT 0,
  created_by     INT           NULL,
  created_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by     INT           NULL,
  updated_at     DATETIME      NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_purchase_orders_no (po_no),
  KEY ix_purchase_orders_supplier (supplier_id, po_status),
  KEY ix_purchase_orders_date (po_date),
  CONSTRAINT fk_purchase_orders_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS purchase_order_items (
  id            INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  po_id         INT UNSIGNED  NOT NULL,
  item_id       INT UNSIGNED  NOT NULL,
  qty           DECIMAL(12,3) NOT NULL,
  received_qty  DECIMAL(12,3) NOT NULL DEFAULT 0,
  rate          DECIMAL(12,2) NOT NULL,
  gst_pct       DECIMAL(5,2)  NOT NULL DEFAULT 0,
  amount        DECIMAL(12,2) NOT NULL,
  gst_amount    DECIMAL(12,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY ix_purchase_order_items_po (po_id),
  KEY ix_purchase_order_items_item (item_id),
  CONSTRAINT fk_purchase_order_items_po   FOREIGN KEY (po_id)   REFERENCES purchase_orders (id),
  CONSTRAINT fk_purchase_order_items_item FOREIGN KEY (item_id) REFERENCES items (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS purchase_entries (
  id                   INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  pe_no                VARCHAR(20)   NOT NULL,
  pe_date              DATE          NOT NULL,
  supplier_id          INT UNSIGNED  NOT NULL,
  po_id                INT UNSIGNED  NULL,
  supplier_invoice_no  VARCHAR(40)   NOT NULL,
  invoice_date         DATE          NOT NULL,
  invoice_file_url     VARCHAR(255)  NULL,
  invoice_file_name    VARCHAR(150)  NULL,
  sub_total            DECIMAL(12,2) NOT NULL DEFAULT 0,
  cgst                 DECIMAL(12,2) NOT NULL DEFAULT 0,
  sgst                 DECIMAL(12,2) NOT NULL DEFAULT 0,
  igst                 DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount             DECIMAL(12,2) NOT NULL DEFAULT 0,
  other_charges        DECIMAL(12,2) NOT NULL DEFAULT 0,
  round_off            DECIMAL(12,2) NOT NULL DEFAULT 0,
  grand_total          DECIMAL(12,2) NOT NULL DEFAULT 0,
  paid_amount          DECIMAL(12,2) NOT NULL DEFAULT 0,
  balance              DECIMAL(12,2) NOT NULL DEFAULT 0,
  due_date             DATE          NULL,
  payment_status       ENUM('UNPAID','PARTIAL','PAID') NOT NULL DEFAULT 'UNPAID',
  is_deleted           TINYINT(1)    NOT NULL DEFAULT 0,
  created_by           INT           NULL,
  created_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by           INT           NULL,
  updated_at           DATETIME      NULL,
  active_invoice       VARCHAR(60)   GENERATED ALWAYS AS (IF(is_deleted = 0, CONCAT(supplier_id, ':', supplier_invoice_no), NULL)) VIRTUAL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_purchase_entries_no (pe_no),
  UNIQUE KEY uq_purchase_entries_invoice (active_invoice),
  KEY ix_purchase_entries_supplier (supplier_id, payment_status),
  KEY ix_purchase_entries_po (po_id),
  KEY ix_purchase_entries_date (pe_date),
  CONSTRAINT fk_purchase_entries_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
  CONSTRAINT fk_purchase_entries_po       FOREIGN KEY (po_id)       REFERENCES purchase_orders (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS purchase_entry_items (
  id            INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  pe_id         INT UNSIGNED  NOT NULL,
  po_item_id    INT UNSIGNED  NULL,
  item_id       INT UNSIGNED  NOT NULL,
  ordered_qty   DECIMAL(12,3) NULL,
  received_qty  DECIMAL(12,3) NOT NULL,
  rate          DECIMAL(12,2) NOT NULL,
  gst_pct       DECIMAL(5,2)  NOT NULL DEFAULT 0,
  expiry_date   DATE          NULL,
  amount        DECIMAL(12,2) NOT NULL,
  cgst          DECIMAL(12,2) NOT NULL DEFAULT 0,
  sgst          DECIMAL(12,2) NOT NULL DEFAULT 0,
  igst          DECIMAL(12,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY ix_purchase_entry_items_pe (pe_id),
  KEY ix_purchase_entry_items_item (item_id),
  KEY ix_purchase_entry_items_po_item (po_item_id),
  CONSTRAINT fk_purchase_entry_items_pe      FOREIGN KEY (pe_id)      REFERENCES purchase_entries (id),
  CONSTRAINT fk_purchase_entry_items_po_item FOREIGN KEY (po_item_id) REFERENCES purchase_order_items (id),
  CONSTRAINT fk_purchase_entry_items_item    FOREIGN KEY (item_id)    REFERENCES items (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS supplier_payments (
  id            INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  supplier_id   INT UNSIGNED  NOT NULL,
  pe_id         INT UNSIGNED  NOT NULL,
  payment_date  DATE          NOT NULL,
  amount        DECIMAL(12,2) NOT NULL,
  payment_mode  ENUM('CASH','BANK','UPI','CHEQUE') NOT NULL,
  reference_no  VARCHAR(50)   NULL,
  created_by    INT           NULL,
  created_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY ix_supplier_payments_supplier (supplier_id, payment_date),
  KEY ix_supplier_payments_pe (pe_id),
  CONSTRAINT fk_supplier_payments_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id),
  CONSTRAINT fk_supplier_payments_pe       FOREIGN KEY (pe_id)       REFERENCES purchase_entries (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
